apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- rollout.yaml
- service-active.yaml
- service-preview.yaml
- namespace.yaml
namespace: nodejs
images:
- name: aks-k8s-rollouts
  newName: asjadsohail/aks-k8s-rollouts
  newTag: 97da1bb2e85d5401e3f7281c5ef26cb33e4dc333
