apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- rollout.yaml
- service-active.yaml
- service-preview.yaml
- namespace.yaml
namespace: nodejs
images:
- name: aks-k8s-rollouts
  newName: asjadsohail/aks-k8s-rollouts
  newTag: aed800e5cf93e8050989b20c699e6a4c993cc865
